name: Deploy Express App

on:
  push:
    branches:
      - main # Modifica se usi un altro branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Specifica la versione di Node.js che stai usando

      - name: Package application
        run: |
          tar --exclude='.git' --exclude='node_modules' --exclude='app.tar.gz' -czf app.tar.gz .

      - name: Upload files via SFTP
        env:
          SFTP_SERVER: ${{ secrets.PLESK_SFTP_SERVER }}
          SFTP_USERNAME: ${{ secrets.PLESK_SFTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.PLESK_SFTP_PASSWORD }}
        run: |
          sudo apt-get update && sudo apt-get install -y lftp
          lftp -u "$SFTP_USERNAME","$SFTP_PASSWORD" sftp://$SFTP_SERVER <<EOF
            set ssl:verify-certificate no
            cd ../var/www/vhosts/spacedesign-italia.it/api.spacedesign-italia.it
            put app.tar.gz
            bye
          EOF

      - name: Extract files and start app with PM2
        env:
          SFTP_SERVER: ${{ secrets.PLESK_SFTP_SERVER }}
          SFTP_USERNAME: ${{ secrets.PLESK_SFTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.PLESK_SFTP_PASSWORD }}
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p "$SFTP_PASSWORD" ssh -o StrictHostKeyChecking=no "$SFTP_USERNAME"@"$SFTP_SERVER" <<EOF
            cd ../var/www/vhosts/spacedesign-italia.it/api.spacedesign-italia.it
            tar -xzf app.tar.gz
            npm install
            pm2 delete api-spacedesign || true  # Rimuove eventuali processi esistenti con lo stesso nome
            pm2 start ./index.js --name api-spacedesign
          EOF
