name: Deploy Spacedesign Aurora API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy to server via SSH and start with PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PLESK_SFTP_SERVER }}
          username: ${{ secrets.PLESK_SFTP_USERNAME }}
          password: ${{ secrets.PLESK_SFTP_PASSWORD }}
          port: 22
          debug: true
          script: |
            echo "=== SSH Connection Test ==="
            hostname
            whoami

            echo "=== Navigating to target directory ==="
            cd /var/www/vhosts/spacedesign-italia.it/api.spacedesign-italia.it || { echo "Directory not found"; exit 1; }

            echo "=== Synchronizing files ==="
            rsync -av --exclude='.git' --exclude='node_modules' ./ .

            echo "=== Installing dependencies ==="
            npm install || { echo "npm install failed"; exit 1; }

            echo "=== Restarting app with PM2 ==="
            pm2 stop spacedesign-aurora-api || true
            pm2 start index.js --name "spacedesign-aurora-api" --watch || { echo "PM2 failed to start"; exit 1; }
            pm2 save
